### PR TITLE
upgrade electron dependence

### PR DESCRIPTION
**Pull request by SnowRunescape**
upgrade dependence electron

### CODE REVIEW

**Comment by mattsgarlata** [comment]
@jerryorr would you please review this?

**Review by jerryorr — APPROVED** [review]
+1

**Comment by SnowRunescape** [comment]
@jerryorr, thank you for the speed of approval, I am very happy.

Can you create a version in npm?
we need to fix a problem

**Comment by mattsgarlata** [comment]
@jerryorr I think there were several other things that needed to go into this change as well, based on the last time you bumped the electron version: https://github.com/fraserxu/electron-pdf/commit/b03284fd8d273094a91de3931be47605ed644224

**Comment by SnowRunescape** [comment]
@mattsgarlata @jerryorr 
https://github.com/fraserxu/electron-pdf/pull/321/files

**Comment by jerryorr** [comment]
@SnowRunescape new verison is on npm https://www.npmjs.com/package/electron-pdf

**Pull request merged**
