### PR TITLE
Let electron-pdf use newer versions of electron

### PR DESCRIPTION
**Pull request by frivoal**

### CODE REVIEW

**Comment by codecounselor** [comment]
I have this locked down and only upgrade intentionally to ensure there are no breaking changes.  If anyone has a compelling reason to bump the version a patch release can be done.

**Comment by frivoal** [comment]
> I have this locked down and only upgrade intentionally to ensure there are no breaking changes.

I see. Makes sense.

> If anyone has a compelling reason to bump the version a patch release can be done.

I do. The version of electron currently used has a bug that causes `<thead>` elements to be rendered in a strange / duplicated way, and that breaks any document that uses them. This is a chromium bug that has since been fixed, and upgrading electron to 1.6 solves that.

https://github.com/electron/electron/issues/8386

**Comment by fraserxu** [comment]
@frivoal Maybe you'll need to upgrade the version number of electron to the fixed version instead of `>=`?

**Comment by frivoal** [comment]
Thanks for the feedback. I've amended the patch accordingly.

**Comment by codecounselor** [comment]
I actually have the same problem and had just disabled them like so:
```
        // Chromium puts table headers in the wrong spot, this turns them off
	// on subsequent pages.  The first header still remains
	thead { display: table-row-group; }
```

I also saw this was fixed in 1.6 but when I did some testing on earlier versions of 1.6 I saw other problems so I kept things on 1.4.x.  I will try with the latest version again today and see what I find.

**Comment by codecounselor** [comment]
So even after upgrading to 1.6.2 I still have the same problem, as seen here:
image

From `process.versions` of my API Server
image

Would you mind posting a before/after screenshot of your tables?  I also have not been able to figure out how to get <tr> breaks to break after and not in the middle of a row.  Have you got that working as well?

**Comment by codecounselor** [comment]
btw, my best guess of what is happening is that wherever the original table headers are positioned is where they show up on subsequent pages when the table breaks beyond one page.  I see this even in the latest version of Chrome (`version 57.0.2987.133 (64-bit)`)

**Comment by codecounselor** [comment]
@frivoal I created a 1.3 branch for Electron 1.6.x - Once we get a little more time on this version I will merge `1.3` into `master`
It has been published to npm as well, I am going to close this PR.

If you have any answer to my questions above that would be greatly appreciated!

**Pull request closed without merging**
