### PR TITLE
Bug Fix: The hash (#) part of urls gets stripped out #202

### PR DESCRIPTION
**Pull request by nkoterba**
Code was always passing {} object into urlWithArgs function and would strip valid, existing, requested URLs with an existing hash out (breaks SPA that use hash to route to different parts of application).  This code looks like it added some functionality that’s no longer used or needed so removing it.

### CODE REVIEW

**Comment by fraserxu** [comment]
Hmm, looks good to me. But I'll need to double check why it was there at the first place and then come back to this later.

**Comment by fraserxu** [comment]
It was originally introduced in this pr https://github.com/fraserxu/electron-pdf/pull/186

**Comment by fraserxu** [comment]
cc @rriclet ^

**Comment by codecounselor** [comment]
I'm hesitant to merge this without some more testing.  I think there probably needs to be some kind of automated test for file based operations.
The closer I look at this, I think this might be breaking that.  I don't have time right now to test it myself.

@fraserxu the original `wargs.js` was added here https://github.com/fraserxu/electron-pdf/commit/ed336c77fc532689c6f0268073a6f64c4911a99a#diff-30b0eaf0508dc8da9ecc1b7044f92bb1

**Comment by nkoterba** [comment]
@codecounselor @fraserxu I can update my PR this week with some unit tests for various url options:
* File-based
* Including query string
* Including multiple query params
* Hash-based urls

I'll try to get it done by the end of this week.  I can also look at why @rriclet originally added in his code...I'm sure there was a legitimate reason but why the function was always being called with empty `{}` seems odd to me and may have been a change after the original feature add.

**Comment by codecounselor** [comment]
That would be greatly appreciated.  And I agree it is puzzling, I tried to leave that alone because I wasn't sure myself.

**Comment by rriclet** [comment]
A PR was created because I wasn't able to generate a PDF with this URL : 
`/home/default/myFile.html?print-pdf`

I just changed two properties in `url.format`. That was a couple months ago, not using your library anymore.

**Comment by codecounselor** [comment]
Closing this, as a similar PR was submitted and this never received tests.

**Pull request closed without merging**
